### ISSUE TITLE
Help to fix elf2e32

### ISSUE THREAD

**Issue by fedor4ever** [mrRosset/E32Explorer#4]
Hi! Can you look at https://github.com/fedor4ever/elf2e32? I stuck and need fresh eye. I dig 2 places but cant undestand why breaks here.
My goal - build latest libressl instead unsupported openssl 0.98.
I try el2e32 from several sdk(s60v5, 9.3 fp2, belle sdk) - they have different bugs. For example only 9.3 fp2 sdk elf2e32 can build python sources. And all of them can't buid e32image from elf. Then I start fix it.
What done: can build with gcc 5.3.0 or visual studio 2015. It runs and produce correct dso and def files.
What not works: can't convert test dll.

**Comment by mrRosset** [comment]
Hi,
I'm not very familiar with Symbian Os v9 and more recent, but on older version of the system you had to compile the code you want for Symbian Os using the provided tools from the SDKs. The toolchain would automatically use petran/elf2e32 to convert the resulting binary into an E32Image format.

I suppose you could compile it yourself against the Symbian Kernel and then manually use the elf2e32 tool to change it's executable format. What step do you use to compile the libressl against the Symbian kernel ?

I searched a bit around for compiling instruction for openssl on Symbian Os but most of what I could find was dead or incomplete. [This discussion](http://web.archive.org/web/20080504010145/http://discussion.forum.nokia.com/forum/showthread.php?t=93263) give a little bit of insight but the links to the makefile and configuration are dead.

**Comment by fedor4ever** [comment]
Hey, elf2e32 broken itself. That's why I can not finish port.

Deep symbian knowledge not needed only deep debug skills on windows, linux, osx etc and any Symbian 9 sdk installed.

I know where elf2e32 fails but cant find why.
Found 2 strange places, maybe more:

1. pl_elfexecutable.cpp - see ElfExecutable::Segment(Elf32_Addr aAddr)
2. e32imagefile.cpp - void E32ImageFile::ProcessSymbolInfo()
