### ISSUE TITLE
Empty releases section

### ISSUE THREAD

**Issue by 1upus** [mrRosset/E32Explorer#5]
Hi. Can you compile last sources to win32 executable?
Thx.

**Comment by mrRosset** [comment]
I've pushed a test release. Can you tell me if it works on your side.
Note: You have to drag and drop the ".app"(or exe, or dll) to the executable to launch it.

**Comment by 1upus** [comment]
I have error with my Win7 x86 compatibility :/
Maybe it's x64 version?

**Comment by mrRosset** [comment]
Yup. I've uploaded a x86 version

**Comment by 1upus** [comment]
Now it works fine. Thank you so much
